config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
    unless ARGV.grep(/assets:(precompile|clean)|db:(migrate)|c|console/).any?
      ActiveAdmin.routes(self)
    end
  devise_for :users
  resources :cars
  resources :messages
  resources :profiles
  resources :orders
  resources :reviews

  get 'dashboard', to: 'orders#home', as: :dashboard
  get 'dashboard/trips/new', to: 'orders#new', as: :new_trip
  get 'dashboard/trips', to: 'orders#index', as: :trips
  get 'dashboard/trips/:id', to: 'orders#show', as: :trip

  post 'help_request', to: 'application#help_request'
  get 'take_order/:id', to: 'orders#driver_take_order'
  get 'complete_order/:id', to: 'orders#complete_order'

  get 'take_position', to: 'orders#take_position'
  get 'find_coords', to: 'orders#find_coords'
  get 'find_place', to: 'orders#find_place'
  
  get 'messages/new_message/:id', to: 'messages#new_message', as: :new_mes
  get 'messages/users/:id', to: 'messages#my_users', as: :user_messages
  get 'messages/user/:id', to: 'messages#user_index'


  root to: 'visitors#index'
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  from_id    :integer
#  to_id      :integer
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Message < ActiveRecord::Base
	validates :text, presence: true
	validates :text, length: { minimum: 5 }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  layout "dashboard.html"

  # search all message where we know our friend
  def user_index
    @to_id = params[:id]
    @messages = Message.where(from_id: [current_user.id, @to_id], to_id: [current_user.id, @to_id]).order("created_at DESC").reverse
    @message = Message.new
  end

  def show
    @messages = Message.where(from_id: current_user.id, to_id: @to_id)
  end

  def new
    @message = Message.new
  end

  def my_users    
  end

  def new_message
    @to_id = params[:id]
    @message = Message.new
  end

  def index
    @messages = Message.where(from_id: current_user.id) || Message.where(to_id: current_user.id)
  end

  # def edit
  # end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to :back, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    #@message.update_attribute(:text, params["new_text"])
    respond_to do |format|
      if @message.update_attribute(:text, params["new_text"])
        #format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        #format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:from_id, :to_id, :text)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
	def find_user (id) 
		user = User.find(id)
	end

	def sender?(id)
		Message.find(id).from_id == current_user.id ? true : false
	end

	def count_messages(id)
		Message.where(from_id: current_user.id, to_id: id).count + Message.where(to_id: current_user.id, from_id: id).count
	end

	def count_sent_messages(id)
		(Message.where(from_id: current_user.id, to_id: id)).count
	end

	def count_incoming_messages(id)
		Message.where(to_id: current_user.id, from_id: id).count
	end	
end

app/views/messages/_form.html.slim
= simple_form_for(@message) do |f|
  = f.error_notification
  .form-inputs
  	.form-group
    = f.hidden_field :from_id, value: current_user.id
   	.form-group
    = f.hidden_field :to_id, value: find_user(user_to).id
    = f.input :text, placeholder: 'New message'

  .form-actions.text-right
    = f.button :submit, id: "cr_message"

app/views/messages/_message_box.html.slim
.row.message-box
	- if sender?(message.id)
		.col-md-10
			.row.message-head
				.col-md-offset-6.col-md-6.padd-right
					= link_to(message, data: {:confirm => 'Are you sure?'}, :method => :delete) do
						i.fa.fa-trash-o
			.message-body
				p.interlocutor
					span#message-text-field
				  	= message.text
			.message-footer
				= message.updated_at.strftime('%c')
		.col-md-2.paper-plane
			i.fa.fa-paper-plane
	- else
		.col-md-2.paper-plane
			i.fa.fa-paper-plane-o
		.col-md-10
			.row.message-head
				.col-md-offset-6.col-md-6.padd-right.padd-right
					= link_to(message, data: {:confirm => 'Are you sure?'}, :method => :delete) do
						i.fa.fa-trash-o
			.message-body
			  p.interlocutor
			  	span#message-text-field
			    	= message.text
			.message-footer
				= message.updated_at.strftime('%c')

app/views/messages/_message_user_box.html.slim
.row.messages-user-box.m-box
	.col-md-2
		span.hidden-id
			= user.id
		span.messages-avatar-male
	.col-md-3
		h3
			= link_to user.name.capitalize , {controller: "profiles", action: "show", id: user.profile.id}
	.col-md-4
		.messages-send-info
			i.fa.fa-envelope
			span
				= count_messages(user.id)
			span
				| all messages
		.messages-send-info
			i.fa.fa-paper-plane
			span
				= count_sent_messages(user.id)
			span
				| sent messages
		.messages-send-info
			i.fa.fa-paper-plane-o
			span
				= count_incoming_messages(user.id)
			span
				| incoming messages
	.col-md-3
		.messages-link
			= link_to "My Conversation", {controller: "messages", action: "user_index", id: user.id}

app/views/messages/edit.html.slim
h1 Editing message

== render 'form'

= link_to 'Show', @message
'|
= link_to 'Back', messages_path

app/views/messages/index.html.slim
h2 INDEX MESSAGES

app/views/messages/my_users.html.slim
h2 Your Interlocutors: 
- current_user.opposite_roles.each do |user|
	= render partial: "message_user_box", locals: { user: user }

app/views/messages/new.html.slim
h1 New message

== render 'form'

= link_to 'Back', messages_path

app/views/messages/new_message.html.slim
span.hidden
	= @to_id 
= render partial: "form", locals: {user_to: @to_id} 

app/views/messages/show.html.slim
h2 Show Message
= render partial: "message_box", locals: { message: @message} 

app/views/messages/user_index.html.slim
- if @messages.any?
  h1 
    | Your chat with 
    = link_to find_user(@messages.first.to_id).name.capitalize , {controller: "profiles", action: "show", id: find_user(@messages.first.to_id).id}, :class => "driver-color"
  hr
  .scrolling-messages.m-box
    .col-md-12
      - @messages.each do |message|
        = render partial: "message_box", locals: { message: message}  
  .message-container
    hr
    .message-field
      .row
        .col-md-12
          .hidden
            = @messages.first.to_id
          .msg-frm
            = render partial: "form", locals: { user_to: @messages.first.to_id}
    hr
    .scrolling-messages
      .row
        .col-md-12
          - @messages.each do |message|
            = render partial: "message_box", locals: { message: message}  
- else
  h1 
    | Your chat with 
    = link_to find_user(@to_id).name.capitalize , {controller: "profiles", action: "show", id: Profile.find_by(user_id: @to_id)}, :class => "driver-color"
  .message-container
    hr
    .message-field
      .row
        .col-md-12
          .hidden
            = @to_id
          .msg-frm
            = render partial: "form", locals: { user_to: @to_id}