config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
    unless ARGV.grep(/assets:(precompile|clean)|db:(migrate)|c|console/).any?
      ActiveAdmin.routes(self)
    end
  devise_for :users
  resources :cars
  resources :messages
  resources :profiles
  resources :orders
  resources :reviews

  get 'dashboard', to: 'orders#home', as: :dashboard
  get 'dashboard/trips/new', to: 'orders#new', as: :new_trip
  get 'dashboard/trips', to: 'orders#index', as: :trips
  get 'dashboard/trips/:id', to: 'orders#show', as: :trip

  post 'help_request', to: 'application#help_request'
  get 'take_order/:id', to: 'orders#driver_take_order'
  get 'complete_order/:id', to: 'orders#complete_order'

  get 'take_position', to: 'orders#take_position'
  get 'find_coords', to: 'orders#find_coords'
  get 'find_place', to: 'orders#find_place'
  
  get 'messages/new_message/:id', to: 'messages#new_message', as: :new_mes
  get 'messages/users/:id', to: 'messages#my_users', as: :user_messages
  get 'messages/user/:id', to: 'messages#user_index'


  root to: 'visitors#index'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  rider_id      :integer
#  driver_id     :integer
#  location_to   :string
#  location_from :string
#  status        :integer          default(0)
#  price         :float
#  description   :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  pessengers    :integer
#  mfrom_lat     :decimal(, )
#  mfrom_lng     :decimal(, )
#  mto_lat       :decimal(, )
#  mto_lng       :decimal(, )
#

class Order < ActiveRecord::Base
  enum status: [:pending, :accepted, :completed]
  has_many :reviews

  include DriverRiderble
  validates :status,
            :price,
            :rider_id,
            :location_to,
            :location_from, presence: true
  validates :pessengers,
            presence: true,
            inclusion: {in: 1..5, message: "You can have a ride for five passengers maximum"}
  # validates :driver_id, presence: true, if: Proc.new {|o| o.status != 0}
  validates :driver_id, presence: true, unless: ->(order) {order.pending?}

  # driver_id prsesnce !pending

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :_set_order, only: [:destroy, :driver_take_order, :complete_order]
  before_filter :authenticate_user!
  layout "dashboard.html", only: [:home, :show, :new, :index]

  def home
    case current_user.role
    when 'rider'
      order = Order.where(rider_id: current_user.id).last
      if (order == nil) || (order.status == 'completed')
        redirect_to :new_trip
      else
        redirect_to trip_path(order)
      end
    when "driver"
      order = Order.where(driver_id: current_user.id).sort_by(&:updated_at).last
      if (order != nil) && (order.status == 'accepted')
        redirect_to  trip_path(order)
      else
        redirect_to :trips, alert: "You haven't any orders in progress."
      end
    else
      redirect_to :trips
    end
  end

  def index
    @orders = case current_user.role
    when 'rider'
      Order.where(rider_id: current_user.id);
    when 'driver'
      Order.where("status = ? or driver_id = ?", status[0], current_user.id)
    else #admin -> all, for debugging
      Order.all
    end
  end

  def show
    order = Order.find(params[:id])
    if current_user.rider? && order.accepted?
      @review = Review.new
    elsif order.completed?
      @review = Review.where(order_id: order.id).take || Review.new
    end
    if _order_viewable?(order)
      @order = order
    else
      redirect_to :dashboard, alert: "Sorry, but You don't have access!"
    end
  end

  def new
    if current_user.role != 'rider'
      redirect_to :root #maybe should redirect to another place??
    end
    order = Order.where(rider_id: current_user.id).last
    if (order == nil) || (order.status == 'completed')
      @order = Order.new
      l1 = ::Location.new(49.82, 24)
      @marker_options = l1.marker_params
      @map_options = l1.map_params
    else
      redirect_to  trip_path(order)
    end
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to :back, notice: "Order was created successfully"
    else
      redirect_to :back, alert: "ERROR: For some reason order wasn't created"
    end
  end

  def destroy
    if _order_destroyable?
      @order.destroy
      respond_to do |format|
        format.json { head :no_content }
        format.html { redirect_to :trips, notice: 'Order was successfully destroyed.' }
      end
    else
      redirect_to :dashboard, alert: 'Sorry but you have not access!'
    end
  end

  def driver_take_order
    if @order.update_attributes(driver_id: current_user.id, status: Order.statuses["accepted"])
      render json: { name: current_user.name, email: current_user.email,
                     phone: current_user.profile.phone, license_plate: current_user.profile.car_phone,
                     date: @order.updated_at.strftime('%c') }
    else
      redirect_to :back, alert: "ERROR: Order wasn't taked"
    end
  end

  def complete_order
    @order.completed!
    StatusMailer.completed_status_email(@order).deliver_later
    render json: { notice: "Order was completed successfully", date: @order.updated_at.strftime('%c') }
  end

  # GOOGLE MAP AJAX
  def take_position
    # IP ::Location
    # ::Location_info = request.::Location
    # l = ::Location.new(::Location_info.latitude, ::Location_info.longitude)
    l = ::Location.new(49.82, 24)

    render json: { marker_options: l.marker_params, map_options: l.map_params }
  end

  def find_coords
    place = Geocoder.coordinates("#{params[:place]}")
    if place.present?
      l = ::Location.new(place[0],place[1])
      render json: { marker_options: l.marker_params }
    else
      redirect_to :back, alert: "ERROR: Can't find this place coordinates"
    end
  end

  def find_place
    place = Geocoder.search("#{params[:lat]},#{params[:lng]}").first
    if place.present?
      render json: { place: place.formatted_address }
    else
      redirect_to :back, alert: "ERROR: This coords are wrong"
    end
  end

  private

    def _order_viewable?(order)
      current_user.admin? || (current_user.rider? && order.rider_id == current_user.id) ||
      (current_user.driver? && (order.driver_id == current_user.id || order.pending?))
    end

    def _order_destroyable?
      current_user.admin? ||
      (current_user.rider? && @order.rider_id == current_user.id && @order.pending?)
    end

    def _set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:rider_id, :location_to, :location_from,
                                     :status, :description, :pessengers,
                                     :mfrom_lat, :mfrom_lng, :mto_lat,
                                     :mto_lng, :price)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.slim
.mini-order
  .order-box
    .row.order-box-header
      - if order.pending?
        .col-md-4.col-sm-6.col-xs-6.status.yellow-line
          = order.status
      - elsif order.accepted?
        .col-md-4.col-sm-6.col-xs-6.status.green-line
          = order.status
      - else
        .col-md-4.col-sm-6.col-xs-6.status.grey-line
          = order.status
      .col-md-offset-4.col-sm-offset-2.col-xs-offset-2.col-md-4.col-sm-4.col-xs-4.links-box
        - if current_user.admin? || (current_user.rider? && order.rider_id == current_user.id && order.pending?)
          i.fa.fa-trash
          = link_to 'Delete', {controller: "orders", action: "destroy", id: order}, data: {:confirm => 'Are you sure?'}, :method => :delete, :remote => true, :class => 'delete-order'
    .order-box-content
      .order-box-order-info
        .col-md-5
          span.order-field-title FROM:
        .col-md-5
          span.order-field-title TO:
        .col-md-5
          span
            = order.location_from
        .col-md-5
          span
            = order.location_to

        .col-md-6
          span
            |By:
            a.little_padding
              = link_to "#{order.rider.name.capitalize}", profile_path(Profile.find_by(user_id: order.rider.id).id)
        .col-md-6.tright
          span
            |in:
            span.little_padding
              = order.created_at.strftime('%c')

      .order-box-buttons
        .col-md-offset-8.col-md-4
          = link_to "Show more", {controller: "orders", action: "show", id: order}, class: "btn btn-grey"

app/views/orders/_new_map.html.slim
= content_tag 'div', '', id: 'data', data: {marker: @marker_options, map: @map_options}
#map_head
	.input-group
	  input#field_from.form-control placeholder=("from...") type="text" value="#{@marker_options[:infowindow]}"
	  span.input-group-btn
	    button#input-from-button.btn.btn-style type="button"  
	    	span class="glyphicon glyphicon-map-marker" aria-hidden="true"
	.input-group
	  input#field_to.form-control placeholder=("to...") type="text"
	  span.input-group-btn
	    button#input-to-button.btn.btn-style type="button"
	    	span class="glyphicon glyphicon-map-marker" aria-hidden="true"
	button#plan_route.btn.btn-style disabled="disabled" type="button"  Plan Route
div style=("width: 100%;") 
  #map style=("width: 100%; height: 300px;")
span &nbsp;*markers are dragable
br/
span &nbsp;**you can set the destination just clicked mouse in the map
br/
span &nbsp;***you can change the current location clicked the left mouse button while keeping the shift

app/views/orders/_order_box.html.slim
.order-box
  .row.order-box-header
    - if order.pending?
      .col-md-4.col-sm-6.col-xs-6.status.yellow-line
        = order.status
    - elsif order.accepted?
      .col-md-4.col-sm-6.col-xs-6.status.green-line
        = order.status
    - else
      .col-md-4.col-sm-6.col-xs-6.status.grey-line
        = order.status
    .col-md-offset-4.col-sm-offset-2.col-xs-offset-2.col-md-4.col-sm-4.col-xs-4.links-box
      - if current_user.admin? || (current_user.rider? && order.rider_id == current_user.id && order.pending?)
        i.fa.fa-trash
        = link_to 'Delete', {controller: "orders", action: "destroy", id: order}, data: {:confirm => 'Are you sure?'}, :method => :delete, :remote => true, :class => 'delete-order'
  .order-box-content
    .order-box-order-info
      .col-md-5
        span.order-field-title FROM:
      .col-md-5
        span.order-field-title TO:
      .col-md-2
        span.order-field-title PASSENGERS:
      .col-md-5
        span
          = order.location_from
      .col-md-5
        span
          = order.location_to
      .col-md-2
        span
          = order.pessengers
      .col-md-10
        span.order-field-title ADDITIONAL INFORMATION:
      .col-md-2
        span.order-field-title PRICE($):
      .col-md-10
        p
          - if order.description.empty?
            | none
          - else
            = order.description
      .col-md-2
        span
          = order.price
    - if order.driver_id != nil
      .order-box-driver-info
        span.order-field-title Driver:
        a.little_padding
          = link_to "#{order.driver.name.capitalize}", profile_path(Profile.find_by(user_id: order.driver.id).id)
        ul
          li
            |email:
            span.little_padding
              = order.driver.email
          li
            |phone_number: 
            span.little_padding
              = order.driver.profile.phone
          li
            |license_plate: 
            span.little_padding
              = order.driver.profile.car_phone
        .col-md-12.tright
          span
            = order.status
          span.little_padding
            |at:
          span.little_padding
          = order.updated_at.strftime('%c')
    - else
      .col-md-6 style ="margin-left: -15px;"
        span
          |by:
        a.little_padding
          = order.rider.name
      .col-md-6.tright
        span
          |in:
        span.little_padding
          = order.created_at.strftime('%c')
    .order-box-buttons
      .col-md-offset-8.col-md-4
        = link_to "Show more", {controller: "orders", action: "show", id: order}, class: "btn btn-grey"

app/views/orders/_show_map.html.slim
= content_tag 'div', '', id: 'small_map_data', data: {m1: marker_from, m2: marker_to}
div style=("width: 100%;")
  #small_map style=("width: 100%; height: 200px;")

app/views/orders/edit.html.slim
h1 Editing order

== render 'form'

= link_to 'Show', @order
'|
= link_to 'Back', orders_path

app/views/orders/index.html.slim
- if @orders.empty?
  - if current_user.rider?
    .warn-tittle-box
      h3 Sorry, but You have no orders yet
      h4 
        | You can create new order by this link 
        = link_to " create order >>", dashboard_path
  - elsif current_user.driver?
    .warn-tittle-box
      h3 Sorry, but all orders already are occupied
      h4 And You don't have any completed orders
- elsif current_user.driver? && @orders.find {|o| o.pending? } == nil
  .warn-tittle-box
    h3 Sorry, but all orders already are occupied
    h4 
      But You can review your last taken orders under
      sub.little_padding
        i.fa.fa-level-down
- @orders.reverse_each do |ord|
  = render partial: "order_box", locals: { order: ord }

app/views/orders/new.html.slim
= render partial: "new_map", locals: { marker: @marker_options, map: @map_options }
a#crtord_btn.btn href="#" role="button" Next >>
#myModal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
        h4.modal-title Your Order
      /! main
      .modal-body
        = form_for @order do |f|
          = f.hidden_field :rider_id, value: current_user.id
          /! = f.hidden_field :status, value: "pending"
          .form-group
            label  Location from:
            = f.text_field :location_from, id: "mw_mfrom", class: "form-control", readonly: true
            = f.hidden_field :mfrom_lat, value: 0, id: 'mw_mfrom_lat'
            = f.hidden_field :mfrom_lng, value: 0, id: 'mw_mfrom_lng'
          .form-group
            label  Location to:
            = f.text_field :location_to, id: "mw_mto", class: "form-control", readonly: true
            = f.hidden_field :mto_lat, value: 0, id: 'mw_mto_lat'
            = f.hidden_field :mto_lng, value: 0, id: 'mw_mto_lng'
          .form-group
            label  Passengers:
            = f.number_field :pessengers, class: "form-control passengers", value: 1, in: 1...6, pattern: '/^[0-9]+#$/'
          .form-group
            label  Additional Information:
            = f.text_area :description, class: "form-control", rows: 3
          .form-group
            label Price($):
            = f.number_field :price, class: "form-control", id: 'mw_price', readonly: true
            = f.submit "Create Order", class: "button info btn submit-btn"

app/views/orders/show.html.slim
- if @order.accepted? && @order.driver_id == current_user.id
  .show-order-title
    h3 Order in progress
- if @order.rider_id == current_user.id && !@order.completed?
  .show-order-title
    h3 Your current order
.order-box
  .row.order-box-header
    - if @order.pending?
      .col-md-4.status.yellow-line
        = @order.status
    - elsif @order.accepted?
      .col-md-4.status.green-line
        = @order.status
    - else
      .col-md-4.status.grey-line
        = @order.status
    .col-md-4
    .col-md-4.links-box
      - if current_user.admin? || (current_user.rider? && @order.rider_id == current_user.id && @order.pending?)
        i.fa.fa-trash
        = link_to 'Delete', {controller: "orders", action: "destroy", id: @order}, data: {:confirm => 'Are you sure?'}, :method => :delete, :class => 'd-order'
  .order-box-content
    .row
      .col-md-5.col-sm-12.col-xs-12
        span.order-field-title FROM:
        br
        span#order-field-mfrom
          = @order.location_from
        br
        span.order-field-title TO:
        br
        span#order-field-mto
          = @order.location_from
        br
        span.order-field-title PASSENGERS:
        br
        span
          = @order.pessengers
        br
        span.order-field-title PRICE($):
        br
        span
          = @order.price
        br
        span.order-field-title ADDITIONAL INFORMATION:
        br
        span#order-field-description
          - if @order.description.empty?
            | none
          - else
            = @order.description
      .col-md-7.col-sm-12.col-xs-12
        = render partial: "show_map", locals: { marker_from: { lat: @order.mfrom_lat, lng: @order.mfrom_lng, infowindow: @order.location_from }, marker_to: { lat: @order.mto_lat, lng: @order.mto_lng, infowindow: @order.location_to } }
        .row
          .col-md-6
            span
              |by:
            a.little_padding
              = link_to "#{@order.rider.name.capitalize}", profile_path(Profile.find_by(user_id: @order.rider.id).id)
          .col-md-6.tright
            span
              |in:
            span.little_padding
              = @order.created_at.strftime('%c')
    - if @order.driver_id != nil
      .order-box-driver-info.padd-top
          span.order-field-title Driver:
          /! make real link!!!
          a.little_padding
          = link_to "#{@order.driver.name.capitalize}", profile_path(Profile.find_by(user_id: @order.driver.id).id)
          ul
            li
              |email:
              span.little_padding
                = @order.driver.email
            li
              |phone_number:
              span.little_padding
                = @order.driver.profile.phone
            li
              |license_plate:
              span.little_padding
                = @order.driver.profile.car_phone
          -if @order.status != "pending"
            #updated_date.col-md-12.tright
              span
                = @order.status
              span.little_padding
                |at:
              span.little_padding
                = @order.updated_at.strftime('%c')
    -if current_user.driver? && @order.pending?
      .row
        .col-md-12.col-sm-12.col-xs-12
          span#hidden_order_id
            = @order.id
          button#take_order.btn.btn-grey type="button" Take order
    - elsif @order.rider_id == current_user.id && @order.accepted?
      .row
        .col-md-12.col-sm-12.col-xs-12
          span#hidden_order_id
            = @order.id
          .row
            .col-md-4.col-md-offset-4
              a#cmplord_btn.btn.btn-orange href="#" role="button" Close order >>
      #reviewModal.modal.fade
        .modal-dialog
          .modal-content
            .modal-header
              button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
              h3.modal-title Thank You for riding with Us.
            /! main
            .modal-body
              = render 'reviews/form'
    - if @order.completed?
      .row
        .col-md-12.col-sm-12.col-xs-12
          span#hidden_order_id
            = @order.id
      .row
        - if @review.text
          = render 'reviews/show'
        - else
          = render 'reviews/form'