config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
    unless ARGV.grep(/assets:(precompile|clean)|db:(migrate)|c|console/).any?
      ActiveAdmin.routes(self)
    end
  devise_for :users
  resources :cars
  resources :messages
  resources :profiles
  resources :orders
  resources :reviews

  get 'dashboard', to: 'orders#home', as: :dashboard
  get 'dashboard/trips/new', to: 'orders#new', as: :new_trip
  get 'dashboard/trips', to: 'orders#index', as: :trips
  get 'dashboard/trips/:id', to: 'orders#show', as: :trip

  post 'help_request', to: 'application#help_request'
  get 'take_order/:id', to: 'orders#driver_take_order'
  get 'complete_order/:id', to: 'orders#complete_order'

  get 'take_position', to: 'orders#take_position'
  get 'find_coords', to: 'orders#find_coords'
  get 'find_place', to: 'orders#find_place'
  
  get 'messages/new_message/:id', to: 'messages#new_message', as: :new_mes
  get 'messages/users/:id', to: 'messages#my_users', as: :user_messages
  get 'messages/user/:id', to: 'messages#user_index'


  root to: 'visitors#index'
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id    :integer          not null, primary key
#  year  :integer
#  brand :string
#  model :string
#

class Car < ActiveRecord::Base
  belongs_to :profile
  validates :year, :brand, :model, presence: true
end

app/controllers/cars_controller.rb
class CarsController < InheritedResources::Base

  private

    def car_params
      params.require(:car).permit(:year, :brand, :model)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.slim
= simple_form_for(@car) do |f|
  = f.error_notification

  .form-inputs
    = f.input :year
    = f.input :brand
    = f.input :model

  .form-actions
    = f.button :submit

app/views/cars/edit.html.slim
h1 Editing car

== render 'form'

= link_to 'Show', @car
'|
= link_to 'Back', cars_path

app/views/cars/index.html.slim
h1 Listing cars

table
  thead
    tr
      th Year
      th Brand
      th Model
      th
      th
      th

  tbody
    - @cars.each do |car|
      tr
        td = car.year
        td = car.brand
        td = car.model
        td = link_to 'Show', car
        td = link_to 'Edit', edit_car_path(car)
        td = link_to 'Destroy', car, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Car', new_car_path

app/views/cars/new.html.slim
h1 New car

== render 'form'

= link_to 'Back', cars_path

app/views/cars/show.html.slim
p#notice = notice

p
  strong Year:
  = @car.year
p
  strong Brand:
  = @car.brand
p
  strong Model:
  = @car.model

= link_to 'Edit', edit_car_path(@car)
'|
= link_to 'Back', cars_path