config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
    unless ARGV.grep(/assets:(precompile|clean)|db:(migrate)|c|console/).any?
      ActiveAdmin.routes(self)
    end
  devise_for :users
  resources :cars
  resources :messages
  resources :profiles
  resources :orders
  resources :reviews

  get 'dashboard', to: 'orders#home', as: :dashboard
  get 'dashboard/trips/new', to: 'orders#new', as: :new_trip
  get 'dashboard/trips', to: 'orders#index', as: :trips
  get 'dashboard/trips/:id', to: 'orders#show', as: :trip

  post 'help_request', to: 'application#help_request'
  get 'take_order/:id', to: 'orders#driver_take_order'
  get 'complete_order/:id', to: 'orders#complete_order'

  get 'take_position', to: 'orders#take_position'
  get 'find_coords', to: 'orders#find_coords'
  get 'find_place', to: 'orders#find_place'
  
  get 'messages/new_message/:id', to: 'messages#new_message', as: :new_mes
  get 'messages/users/:id', to: 'messages#my_users', as: :user_messages
  get 'messages/user/:id', to: 'messages#user_index'


  root to: 'visitors#index'
end

app/views/layouts/_chat_panel.html.slim
button.toggle-messages.btn#pollSlider-button
  i.fa.fa-envelope
  Hide
.d-messages.pollSlider
  h2 Chat
  .related-block
    - current_user.opposite_roles.each do |user|
      .messages-box
        .messages-avatar-male
        h4 = user.name.capitalize
        = link_to "conversation", "/messages/user/#{user.id}", class:('btn-style btn message-btn')
javascript:
  var slider_width = $('.pollSlider').width(); //get width automaticly
  $('#pollSlider-button').click(function() {
    if($(this).css("margin-right") == slider_width+"px" && !$(this).is(':animated')){
      $('.pollSlider,#pollSlider-button').animate({"margin-right": '-='+slider_width});
    } else {
      if(!$(this).is(':animated')){
        $('.pollSlider,#pollSlider-button').animate({"margin-right": '+='+slider_width});
      }
    }
  });

app/views/layouts/_dashboard_sidebar.html.slim
.d-sidebar-nav
  .list-group
    = link_to "Home", dashboard_path, class: "list-group-item"
    = link_to "Orders(Trips)", trips_path, class: "list-group-item"
    = link_to "Messages", "/messages/users/#{current_user.id}", class: "list-group-item"
    = link_to "My Profile", profile_path(Profile.find_by(user_id: current_user.id).id), class: "list-group-item"
.d-sidebar-current-trip
  h3 Current Trip Information:
  - if find_current_order != nil
    #sidebar-current-order
      .row
        .col-md-3.col-sm-4.col-xs-12.head
          |STATUS:
        .col-md-9.col-sm-8.col-xs-12
          = find_current_order.status
      .row
        .col-md-3.col-sm-4.col-xs-12.head
          |FROM:
        .col-md-9.col-sm-8.col-xs-12
          = find_current_order.location_from
      .row
        .col-md-3.col-sm-4.col-xs-12.head
          |TO:
        .col-md-9.col-sm-8.col-xs-12
          = find_current_order.location_to
      .row
        .col-md-12.col-sm-12.col-xs-12
          span.head
            |ADDITIONAL INFORMATION:
          span.little_padding
            - if find_current_order.description.empty?
              |none
            - else
              = find_current_order.description
      .row
        .col-md-12.tright
          = link_to "more..", find_current_order
  - else
    #sidebar-empty-current-order
      h4 No order in progress now

app/views/layouts/_footer.html.slim
.footer.bg-primary
  .container
    .row
      .col-lg-10.col-lg-offset-1.text-center
        h4
          strong YBER
        p
          | 1а Kamyanetska street
          br
          | Ukraine Lviv 79034
        ul.list-unstyled
          li
            i.fa.fa-phone.fa-fw
            | +38 (067) 675-24-50
          li
            i.fa.fa-envelope-o.fa-fw
            a.mailto href="mailto:name@example.com" yber@example.com
        br
        ul.list-inline
          li
            a href="https://www.facebook.com/Lviv.QA.School"
              i.fa.fa-facebook.fa-fw.fa-3x
          li
            a href="https://github.com/lits-ruby-and-rails-course/yber"
              i.fa.fa-github.fa-fw.fa-3x
          li
            a href="https://www.linkedin.com/company/lits-lviv-it-schools-"
              i.fa.fa-linkedin.fa-fw.fa-3x
        br
        p.text-muted Copyright &copy; YBER 2015

app/views/layouts/_help_request.html.slim
div id="help_request"
  button#help_button Help
  h1 Help form
  hr
  = form_for Help.new,  as: :help, url: help_request_path do |f|
  
    = f.label :name
    br
    br
    = f.text_field :name, class: 'form-control hr-form-control',
                          placeholder: 'your name'
    
    = f.label :email
    br
    br 
    = f.text_field :email, class: 'form-control hr-form-control',
                           placeholder: "#{placeholder_email}"
    
    = f.label :message
    br
    br 
    = f.text_area :message, class: 'form-control hr-form-control',
                             placeholder: 'your message'
    br
    br
    = f.submit 'Send', class: 'btn btn-primary'

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true" style="float: left; margin-right: 20px;"
] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
header
  a#menu-toggle.btn.btn-dark.btn-lg.toggle
    i.fa.fa-bars
  = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<nav id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
    <li class="sidebar-brand">
      <a href="visitors/index#top" onclick = $("#menu-close").click(); >YBER</a>
    </li>
    <li>
      <a href="visitors/index#top" onclick = $("#menu-close").click(); >Home</a>
    </li>
    <li>
      <a href="visitors/index#about" onclick = $("#menu-close").click(); >About</a>
    </li>
    <% if user_signed_in? %>
      <li>
        <a href="/dashboard" onclick = $("#menu-close").click(); >Your Dashboard</a>
      </li>
      <li>
        <a href="/users/sign_out" data-method="delete" onclick = $("#menu-close").click(); >Sign Out</a>
      </li>
    <% else %>
      <li>
        <a href="visitors/index#registration" onclick = $("#menu-close").click(); >Sign In</a>
      </li>
      <li>
        <a href="visitors/index#registration" onclick = $("#menu-close").click(); >Sign Up</a>
      </li>
    <% end %>
    <li>
      <a href="visitors/index#portfolio" onclick = $("#menu-close").click(); >Portfolio</a>
    </li>
    <li>
      <a href="visitors/index#contact" onclick = $("#menu-close").click(); >Contact</a>
    </li>
  </ul>
</nav>


<script type="text/javascript">

// Closes the sidebar menu
$("#menu-close").click(function(e) {
  e.preventDefault();
  $("#sidebar-wrapper").toggleClass("active");
});

// Opens the sidebar menu
$("#menu-toggle").click(function(e) {
  e.preventDefault();
  $("#sidebar-wrapper").toggleClass("active");
});

// Scrolls to the selected menu item on the page
$(function() {
  $('a[href*=#]:not([href=#])').click(function() {
    if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
      if (target.length) {
        $('html,body').animate({
          scrollTop: target.offset().top
        }, 1000);
        return false;
      }
    }
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "YBER" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "YBER" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  </head>
  <body>
      <%= render 'layouts/messages' %>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/help_request' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/dashboard.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title
      = content_for?(:title) ? yield(:title) : "YBER"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Yber'}"
    == stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
    link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css"
    script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="
    script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"
    script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js" type="text/javascript"
    /! only if you need custom infoboxes
  body.container-fluid.nopadding
    .row
      .col-md-12.col-sm-12.col-xs-12
        .warnmessage
          p.notice
            = notice
          p.alert
            = alert
    .row.d-header.nopadding
      .col-md-3.col-sm-6.col-xs-12.d-logo
        .logo
          = link_to dashboard_path, class: "title-link" do
            = image_tag("logo_1.png", size: "100x100", title: "Home", alt: "Logo")
            span YBER
      .col-md-6
      .col-md-3.col-sm-6.col-xs-12
        .d-topright
          = link_to "#{current_user.name.capitalize} ", profile_path(current_profile.id)
          | |
          = link_to('Logout', destroy_user_session_path, :method => :delete)
    .row
    .col-md-4.col-sm-4.col-xs-12
      .row.nopadding
        .col-md-10.col-sm-12.col-xs-12.d-sidebar
          = render 'layouts/dashboard_sidebar'
        .col-md-2.col-sm-2.col-xs-2
    .col-md-7.col-sm-7.col-xs-12
      .row
        .col-md-12.col-sm-12.col-xs-12
          .row
            .col-md-12.col-sm-12.col-xs-12
              .row
                .col-md-12.col-sm-12.col-xs-12
                  .d-statistic
                    - if current_user.driver?
                      p
                        | Your current rating:
                      p#stars-dashboard.starrr data-rating=user_rating
                      p
                        | You've accepted
                        = rides_count
                        |  rides

                    - if current_user.rider?
                      p
                        | Your current balance: 357 UAH
                      p
                        | You've had
                        = rides_count
                        |  rides
                    p
                      | Location:
                      = current_profile.city.capitalize
              .row
                .col-md-12.col-sm-12.col-xs-12
                  = yield
        .col-md-3.col-sm-3.col-xs-12
          = render 'layouts/chat_panel'